In [1]:
import torch

In [7]:
if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is not available")

GPU is available


In [9]:
x = torch.arange(12)
x, x.shape, x.numel(), x.reshape(3,4), x.reshape(-1,4)

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 torch.Size([12]),
 12,
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [14]:
torch.zeros((2, 3, 4)), torch.ones((2, 3, 4))

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [15]:
torch.randn(3, 4) # num ~ N(0,1)

tensor([[ 0.6999,  0.8071, -0.7160,  0.1661],
        [-1.6778, -0.3045, -1.6938,  1.2952],
        [ 0.0719, -0.7568,  1.4097,  0.0128]])